#!/bin/python3
import sys
import argparse

def main():
    options = dict(
        config_output_format = 'json',
        config_output_dir = './output/',
        config_output_file = 'output-{concurrency:03d}.json',
        config_storage_type = 'local',
        config_dataset_file = 'datasets/openorca_large_subset_011.jsonl',
        config_dataset_max_queries = 1000,
        config_dataset_min_input_tokens = 0,
        config_dataset_max_input_tokens = 1024,
        config_dataset_min_output_tokens = 0,
        config_dataset_max_output_tokens = 1024,
        config_dataset_max_sequence_tokens = 2048,
        config_load_options_type = 'constant',
        config_load_options_concurrency = 1,
        config_load_options_duration = 20,
        config_plugin = 'openai_plugin',
        config_plugin_options_use_tls = False,
        config_plugin_options_streaming = True,
        config_plugin_options_model_name = 'flan-t5-small',
        config_plugin_options_host = 'http://route.to.host',
        config_plugin_options_endpoint = '/v1/completions',
        config_extra_metadata_replicas = 1
    )

    parser = argparse.ArgumentParser()

    for option_name, option_default in options.items():
        parser.add_argument(f"--{option_name}", default=option_default)

    args = parser.parse_args()

    print(args)

    sys.exit(0)

if __name__ == "__main__":
    main()
